### ISSUE TITLE
Automatically upload to MyGet

### ISSUE THREAD

**Issue by rprouse** [nunit/NUnit.System.Linq#2]
I have uploaded the latest from master to MyGet to use in the 3.4 release. If we ever make additional changes to this repo, we should have AppVeyor automatically publish to MyGet.

**Comment by CharliePoole** [comment]
That's odd. I thought I already had it set up that way.

**Comment by CharliePoole** [comment]
I checked... all builds of master are deployed to MyGet. That's how I got the first one out there. 

The master build only comes out when you merge to master, not before. It will have the -CI pre-release suffix unless you tag it with the version you want to use before merging.

Should we do a re-release of this to make sure and then document the steps?

**Comment by rprouse** [comment]
Okay, I think we need to document the process then. I was confused when I didn't see the new version. I think the 3.4 release is fine as is since it includes the compiled version, but I agree that we should do a non-CI version and start consuming that in NUnit.

**Comment by CharliePoole** [comment]
I'll add it to the README and then step through to make sure it's right.

**Comment by CharliePoole** [comment]
The current fix is more semi-automatic than automatic. To do a non-CI release build you have to specify the version number three times - two files plus a tag. I've created a new issue to automate it with GitVersion. For now, we should use the process documented in the README.
